name: Publish to NPM

on:
  push:
    branches: main

jobs:
  npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: "https://registry.npmjs.org"
    - run: npm publish --access public
